### ISSUE TITLE
Can't find the vpsolver_scip.sh for SCIP optimizer 

### ISSUE THREAD

**Issue by jbsdadilet** [fdabrandao/vpsolver#3]
Hello, 
I have completed the following in Ubuntu:
"sudo apt-get install make"
"sudo apt-get install bash"
"sudo apt-get install gcc"
 "sudo pip3 install pyvpsolver" 
However, running script suing SCIP optimizer providing me below error.
Did I miss some steps of pyvpsolver on Ubuntu? 

>>> vbpsol...
VPSolver 3.1.2, Copyright (C) 2013-2016, Filipe Brandao
free(): double free detected in tcache 2
/home/adilet/.local/bin/vpsolver_scip.sh: line 186:  6344 Aborted                 (core dumped) vbpsol $afg_file $TMP_DIR/vars.sol $vbpsol_opts
Traceback (most recent call last):
  File "1s.py", line 107, in <module>
    raw_solution = solve(order_q, order_b, inventory, cost, solver)
  File "1s.py", line 41, in solve
    output, solution = VPSolver.script(solver_dict[solver], instance)
  File "/home/adilet/.local/lib/python3.8/site-packages/pyvpsolver/vpsolver.py", line 570, in script
    VPSolver.run(cmd, tee=out_file, verbose=verbose)
  File "/home/adilet/.local/lib/python3.8/site-packages/pyvpsolver/vpsolver.py", line 421, in run
    raise RuntimeError("failed to run '{}'".format(cmd))
RuntimeError: failed to run 'vpsolver_scip.sh --mvp /tmp/tmphk0uhzjl/0.mvp --pyout'

**Comment by S1LV3RJ1NX** [comment]
You need to have SCIP installed in the machine first. 
Go to: https://scipopt.org/#download and download [scipoptsuite-8.0.1.tgz](https://scipopt.org/download.php?fname=scipoptsuite-8.0.1.tgz) You can have an academic licensed version of that.

```
Compiling SCIP directly can be done as follows:

1) unpack the tarball "tar xvzf scipoptsuit-x.y.z.tgz"
2) change into the directory "cd scipoptsuit-x.y.z"
3) start compiling SCIP "make"
3) (recommended) check your SCIP installation "make test"
4) install the header, libraries, and binary, e.g.,
   "make install INSTALLDIR="/usr/local/"
```
